# -*- coding: utf-8 -*-
##
## This file is part of setuptools-bower
## Copyright (C) 2013, 2014 CERN.
##
## setuptools-bower is free software; you can redistribute it and/or
## modify it under the terms of the Revised BSD License; see LICENSE
## file for more details.

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - npm install -g bower
  - pip install --upgrade pip  --use-mirrors
  - pip install coveralls pep8 pep257 sphinx --use-mirrors
  - pip install .

script:
  - sphinx-build -qnNW docs docs/_build/html
  - coverage run setup.py test
  - pep8 --ignore=E265 setuptools_bower
  - pep257 setuptools_bower

after_success:
  - coveralls

notifications:
  email: false
